/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CastingRouteImport } from './routes/casting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as FilmsIndexRouteImport } from './routes/films.index'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as NewsletterManageRouteImport } from './routes/newsletter.manage'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as PartnerWithHlsIndexRouteImport } from './routes/partner-with-hls.index'
import { Route as PartnerWithHlsStatusRouteImport } from './routes/partner-with-hls.status'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as PartnersAutomotiveRouteImport } from './routes/partners.automotive'
import { Route as PartnersConfidentialInquiryRouteImport } from './routes/partners.confidential-inquiry'
import { Route as PartnersEducationRouteImport } from './routes/partners.education'
import { Route as PartnersFoundingPartnersRouteImport } from './routes/partners.founding-partners'
import { Route as PartnersNamingRightsRouteImport } from './routes/partners.naming-rights'
import { Route as PartnersProductionSponsorshipsRouteImport } from './routes/partners.production-sponsorships'
import { Route as PartnersStudioDevelopmentRouteImport } from './routes/partners.studio-development'
import { Route as PartnersTechnologyRouteImport } from './routes/partners.technology'
import { Route as AuthenticatedAdminCommunicationsRouteImport } from './routes/_authenticated/admin.communications'
import { Route as AuthenticatedAdminCompanyRouteImport } from './routes/_authenticated/admin.company'
import { Route as AuthenticatedAdminFilmsRouteImport } from './routes/_authenticated/admin.films'
import { Route as ApiPublicEmbedDotjsRouteImport } from './routes/api/public/embed[.]js'
import { Route as ApiPublicBrandSplatRouteImport } from './routes/api/public/brand/$'
import { Route as ApiPublicCrmLeadStageRouteImport } from './routes/api/public/crm/lead-stage'
import { Route as ApiPublicFilmMediaSplatRouteImport } from './routes/api/public/film-media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingRoute = CastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterManageRoute = NewsletterManageRouteImport.update({
  id: '/newsletter/manage',
  path: '/newsletter/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithHlsIndexRoute = PartnerWithHlsIndexRouteImport.update({
  id: '/partner-with-hls/',
  path: '/partner-with-hls/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithHlsStatusRoute = PartnerWithHlsStatusRouteImport.update({
  id: '/partner-with-hls/status',
  path: '/partner-with-hls/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersAutomotiveRoute = PartnersAutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersConfidentialInquiryRoute =
  PartnersConfidentialInquiryRouteImport.update({
    id: '/confidential-inquiry',
    path: '/confidential-inquiry',
    getParentRoute: () => PartnersRoute,
  } as any)
const PartnersEducationRoute = PartnersEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersFoundingPartnersRoute =
  PartnersFoundingPartnersRouteImport.update({
    id: '/founding-partners',
    path: '/founding-partners',
    getParentRoute: () => PartnersRoute,
  } as any)
const PartnersNamingRightsRoute = PartnersNamingRightsRouteImport.update({
  id: '/naming-rights',
  path: '/naming-rights',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersProductionSponsorshipsRoute =
  PartnersProductionSponsorshipsRouteImport.update({
    id: '/production-sponsorships',
    path: '/production-sponsorships',
    getParentRoute: () => PartnersRoute,
  } as any)
const PartnersStudioDevelopmentRoute =
  PartnersStudioDevelopmentRouteImport.update({
    id: '/studio-development',
    path: '/studio-development',
    getParentRoute: () => PartnersRoute,
  } as any)
const PartnersTechnologyRoute = PartnersTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => PartnersRoute,
} as any)
const AuthenticatedAdminCommunicationsRoute =
  AuthenticatedAdminCommunicationsRouteImport.update({
    id: '/admin/communications',
    path: '/admin/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompanyRoute =
  AuthenticatedAdminCompanyRouteImport.update({
    id: '/admin/company',
    path: '/admin/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFilmsRoute = AuthenticatedAdminFilmsRouteImport.update({
  id: '/admin/films',
  path: '/admin/films',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicEmbedDotjsRoute = ApiPublicEmbedDotjsRouteImport.update({
  id: '/api/public/embed.js',
  path: '/api/public/embed.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandSplatRoute = ApiPublicBrandSplatRouteImport.update({
  id: '/api/public/brand/$',
  path: '/api/public/brand/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmLeadStageRoute = ApiPublicCrmLeadStageRouteImport.update({
  id: '/api/public/crm/lead-stage',
  path: '/api/public/crm/lead-stage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFilmMediaSplatRoute = ApiPublicFilmMediaSplatRouteImport.update({
  id: '/api/public/film-media/$',
  path: '/api/public/film-media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/international': typeof InternationalRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/portal': typeof PortalRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/talent': typeof TalentRoute
  '/terms': typeof TermsRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/partner-with-hls/status': typeof PartnerWithHlsStatusRoute
  '/partners/automotive': typeof PartnersAutomotiveRoute
  '/partners/confidential-inquiry': typeof PartnersConfidentialInquiryRoute
  '/partners/education': typeof PartnersEducationRoute
  '/partners/founding-partners': typeof PartnersFoundingPartnersRoute
  '/partners/naming-rights': typeof PartnersNamingRightsRoute
  '/partners/production-sponsorships': typeof PartnersProductionSponsorshipsRoute
  '/partners/studio-development': typeof PartnersStudioDevelopmentRoute
  '/partners/technology': typeof PartnersTechnologyRoute
  '/films/': typeof FilmsIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/partner-with-hls/': typeof PartnerWithHlsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/admin/communications': typeof AuthenticatedAdminCommunicationsRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/films': typeof AuthenticatedAdminFilmsRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/crm/lead-stage': typeof ApiPublicCrmLeadStageRoute
  '/api/public/film-media/$': typeof ApiPublicFilmMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/international': typeof InternationalRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/talent': typeof TalentRoute
  '/terms': typeof TermsRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/partner-with-hls/status': typeof PartnerWithHlsStatusRoute
  '/partners/automotive': typeof PartnersAutomotiveRoute
  '/partners/confidential-inquiry': typeof PartnersConfidentialInquiryRoute
  '/partners/education': typeof PartnersEducationRoute
  '/partners/founding-partners': typeof PartnersFoundingPartnersRoute
  '/partners/naming-rights': typeof PartnersNamingRightsRoute
  '/partners/production-sponsorships': typeof PartnersProductionSponsorshipsRoute
  '/partners/studio-development': typeof PartnersStudioDevelopmentRoute
  '/partners/technology': typeof PartnersTechnologyRoute
  '/films': typeof FilmsIndexRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/partner-with-hls': typeof PartnerWithHlsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/admin/communications': typeof AuthenticatedAdminCommunicationsRoute
  '/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/admin/films': typeof AuthenticatedAdminFilmsRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/crm/lead-stage': typeof ApiPublicCrmLeadStageRoute
  '/api/public/film-media/$': typeof ApiPublicFilmMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy': typeof AcademyRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/international': typeof InternationalRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/portal': typeof PortalRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/talent': typeof TalentRoute
  '/terms': typeof TermsRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/partner-with-hls/status': typeof PartnerWithHlsStatusRoute
  '/partners/automotive': typeof PartnersAutomotiveRoute
  '/partners/confidential-inquiry': typeof PartnersConfidentialInquiryRoute
  '/partners/education': typeof PartnersEducationRoute
  '/partners/founding-partners': typeof PartnersFoundingPartnersRoute
  '/partners/naming-rights': typeof PartnersNamingRightsRoute
  '/partners/production-sponsorships': typeof PartnersProductionSponsorshipsRoute
  '/partners/studio-development': typeof PartnersStudioDevelopmentRoute
  '/partners/technology': typeof PartnersTechnologyRoute
  '/films/': typeof FilmsIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/partner-with-hls/': typeof PartnerWithHlsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/_authenticated/admin/communications': typeof AuthenticatedAdminCommunicationsRoute
  '/_authenticated/admin/company': typeof AuthenticatedAdminCompanyRoute
  '/_authenticated/admin/films': typeof AuthenticatedAdminFilmsRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/crm/lead-stage': typeof ApiPublicCrmLeadStageRoute
  '/api/public/film-media/$': typeof ApiPublicFilmMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/accessibility'
    | '/auth'
    | '/careers'
    | '/casting'
    | '/contact'
    | '/development'
    | '/international'
    | '/news'
    | '/partners'
    | '/portal'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/talent'
    | '/terms'
    | '/films/$slug'
    | '/newsletter/confirm'
    | '/newsletter/manage'
    | '/newsletter/unsubscribe'
    | '/partner-with-hls/status'
    | '/partners/automotive'
    | '/partners/confidential-inquiry'
    | '/partners/education'
    | '/partners/founding-partners'
    | '/partners/naming-rights'
    | '/partners/production-sponsorships'
    | '/partners/studio-development'
    | '/partners/technology'
    | '/films/'
    | '/newsletter/'
    | '/partner-with-hls/'
    | '/partners/'
    | '/admin/communications'
    | '/admin/company'
    | '/admin/films'
    | '/api/public/embed.js'
    | '/api/public/brand/$'
    | '/api/public/crm/lead-stage'
    | '/api/public/film-media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/accessibility'
    | '/auth'
    | '/careers'
    | '/casting'
    | '/contact'
    | '/development'
    | '/international'
    | '/news'
    | '/portal'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/talent'
    | '/terms'
    | '/films/$slug'
    | '/newsletter/confirm'
    | '/newsletter/manage'
    | '/newsletter/unsubscribe'
    | '/partner-with-hls/status'
    | '/partners/automotive'
    | '/partners/confidential-inquiry'
    | '/partners/education'
    | '/partners/founding-partners'
    | '/partners/naming-rights'
    | '/partners/production-sponsorships'
    | '/partners/studio-development'
    | '/partners/technology'
    | '/films'
    | '/newsletter'
    | '/partner-with-hls'
    | '/partners'
    | '/admin/communications'
    | '/admin/company'
    | '/admin/films'
    | '/api/public/embed.js'
    | '/api/public/brand/$'
    | '/api/public/crm/lead-stage'
    | '/api/public/film-media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy'
    | '/accessibility'
    | '/auth'
    | '/careers'
    | '/casting'
    | '/contact'
    | '/development'
    | '/international'
    | '/news'
    | '/partners'
    | '/portal'
    | '/press'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/talent'
    | '/terms'
    | '/films/$slug'
    | '/newsletter/confirm'
    | '/newsletter/manage'
    | '/newsletter/unsubscribe'
    | '/partner-with-hls/status'
    | '/partners/automotive'
    | '/partners/confidential-inquiry'
    | '/partners/education'
    | '/partners/founding-partners'
    | '/partners/naming-rights'
    | '/partners/production-sponsorships'
    | '/partners/studio-development'
    | '/partners/technology'
    | '/films/'
    | '/newsletter/'
    | '/partner-with-hls/'
    | '/partners/'
    | '/_authenticated/admin/communications'
    | '/_authenticated/admin/company'
    | '/_authenticated/admin/films'
    | '/api/public/embed.js'
    | '/api/public/brand/$'
    | '/api/public/crm/lead-stage'
    | '/api/public/film-media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademyRoute: typeof AcademyRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CastingRoute: typeof CastingRoute
  ContactRoute: typeof ContactRoute
  DevelopmentRoute: typeof DevelopmentRoute
  InternationalRoute: typeof InternationalRoute
  NewsRoute: typeof NewsRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PortalRoute: typeof PortalRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TalentRoute: typeof TalentRoute
  TermsRoute: typeof TermsRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  NewsletterManageRoute: typeof NewsletterManageRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  PartnerWithHlsStatusRoute: typeof PartnerWithHlsStatusRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
  PartnerWithHlsIndexRoute: typeof PartnerWithHlsIndexRoute
  ApiPublicEmbedDotjsRoute: typeof ApiPublicEmbedDotjsRoute
  ApiPublicBrandSplatRoute: typeof ApiPublicBrandSplatRoute
  ApiPublicCrmLeadStageRoute: typeof ApiPublicCrmLeadStageRoute
  ApiPublicFilmMediaSplatRoute: typeof ApiPublicFilmMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting': {
      id: '/casting'
      path: '/casting'
      fullPath: '/casting'
      preLoaderRoute: typeof CastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/manage': {
      id: '/newsletter/manage'
      path: '/newsletter/manage'
      fullPath: '/newsletter/manage'
      preLoaderRoute: typeof NewsletterManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-hls/': {
      id: '/partner-with-hls/'
      path: '/partner-with-hls'
      fullPath: '/partner-with-hls/'
      preLoaderRoute: typeof PartnerWithHlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-hls/status': {
      id: '/partner-with-hls/status'
      path: '/partner-with-hls/status'
      fullPath: '/partner-with-hls/status'
      preLoaderRoute: typeof PartnerWithHlsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/automotive': {
      id: '/partners/automotive'
      path: '/automotive'
      fullPath: '/partners/automotive'
      preLoaderRoute: typeof PartnersAutomotiveRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/confidential-inquiry': {
      id: '/partners/confidential-inquiry'
      path: '/confidential-inquiry'
      fullPath: '/partners/confidential-inquiry'
      preLoaderRoute: typeof PartnersConfidentialInquiryRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/education': {
      id: '/partners/education'
      path: '/education'
      fullPath: '/partners/education'
      preLoaderRoute: typeof PartnersEducationRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/founding-partners': {
      id: '/partners/founding-partners'
      path: '/founding-partners'
      fullPath: '/partners/founding-partners'
      preLoaderRoute: typeof PartnersFoundingPartnersRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/naming-rights': {
      id: '/partners/naming-rights'
      path: '/naming-rights'
      fullPath: '/partners/naming-rights'
      preLoaderRoute: typeof PartnersNamingRightsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/production-sponsorships': {
      id: '/partners/production-sponsorships'
      path: '/production-sponsorships'
      fullPath: '/partners/production-sponsorships'
      preLoaderRoute: typeof PartnersProductionSponsorshipsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/studio-development': {
      id: '/partners/studio-development'
      path: '/studio-development'
      fullPath: '/partners/studio-development'
      preLoaderRoute: typeof PartnersStudioDevelopmentRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/technology': {
      id: '/partners/technology'
      path: '/technology'
      fullPath: '/partners/technology'
      preLoaderRoute: typeof PartnersTechnologyRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/_authenticated/admin/communications': {
      id: '/_authenticated/admin/communications'
      path: '/admin/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AuthenticatedAdminCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/company': {
      id: '/_authenticated/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AuthenticatedAdminCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/films': {
      id: '/_authenticated/admin/films'
      path: '/admin/films'
      fullPath: '/admin/films'
      preLoaderRoute: typeof AuthenticatedAdminFilmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/embed.js': {
      id: '/api/public/embed.js'
      path: '/api/public/embed.js'
      fullPath: '/api/public/embed.js'
      preLoaderRoute: typeof ApiPublicEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand/$': {
      id: '/api/public/brand/$'
      path: '/api/public/brand/$'
      fullPath: '/api/public/brand/$'
      preLoaderRoute: typeof ApiPublicBrandSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/lead-stage': {
      id: '/api/public/crm/lead-stage'
      path: '/api/public/crm/lead-stage'
      fullPath: '/api/public/crm/lead-stage'
      preLoaderRoute: typeof ApiPublicCrmLeadStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/film-media/$': {
      id: '/api/public/film-media/$'
      path: '/api/public/film-media/$'
      fullPath: '/api/public/film-media/$'
      preLoaderRoute: typeof ApiPublicFilmMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCommunicationsRoute: typeof AuthenticatedAdminCommunicationsRoute
  AuthenticatedAdminCompanyRoute: typeof AuthenticatedAdminCompanyRoute
  AuthenticatedAdminFilmsRoute: typeof AuthenticatedAdminFilmsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCommunicationsRoute: AuthenticatedAdminCommunicationsRoute,
  AuthenticatedAdminCompanyRoute: AuthenticatedAdminCompanyRoute,
  AuthenticatedAdminFilmsRoute: AuthenticatedAdminFilmsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PartnersRouteChildren {
  PartnersAutomotiveRoute: typeof PartnersAutomotiveRoute
  PartnersConfidentialInquiryRoute: typeof PartnersConfidentialInquiryRoute
  PartnersEducationRoute: typeof PartnersEducationRoute
  PartnersFoundingPartnersRoute: typeof PartnersFoundingPartnersRoute
  PartnersNamingRightsRoute: typeof PartnersNamingRightsRoute
  PartnersProductionSponsorshipsRoute: typeof PartnersProductionSponsorshipsRoute
  PartnersStudioDevelopmentRoute: typeof PartnersStudioDevelopmentRoute
  PartnersTechnologyRoute: typeof PartnersTechnologyRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersAutomotiveRoute: PartnersAutomotiveRoute,
  PartnersConfidentialInquiryRoute: PartnersConfidentialInquiryRoute,
  PartnersEducationRoute: PartnersEducationRoute,
  PartnersFoundingPartnersRoute: PartnersFoundingPartnersRoute,
  PartnersNamingRightsRoute: PartnersNamingRightsRoute,
  PartnersProductionSponsorshipsRoute: PartnersProductionSponsorshipsRoute,
  PartnersStudioDevelopmentRoute: PartnersStudioDevelopmentRoute,
  PartnersTechnologyRoute: PartnersTechnologyRoute,
  PartnersIndexRoute: PartnersIndexRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademyRoute: AcademyRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CastingRoute: CastingRoute,
  ContactRoute: ContactRoute,
  DevelopmentRoute: DevelopmentRoute,
  InternationalRoute: InternationalRoute,
  NewsRoute: NewsRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PortalRoute: PortalRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TalentRoute: TalentRoute,
  TermsRoute: TermsRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  NewsletterManageRoute: NewsletterManageRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  PartnerWithHlsStatusRoute: PartnerWithHlsStatusRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
  PartnerWithHlsIndexRoute: PartnerWithHlsIndexRoute,
  ApiPublicEmbedDotjsRoute: ApiPublicEmbedDotjsRoute,
  ApiPublicBrandSplatRoute: ApiPublicBrandSplatRoute,
  ApiPublicCrmLeadStageRoute: ApiPublicCrmLeadStageRoute,
  ApiPublicFilmMediaSplatRoute: ApiPublicFilmMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
